### ISSUE TITLE
订阅错误

### ISSUE THREAD

**Issue by TANGCHUN1979** [fgprodigal/OpenWrtx86_64-firmware#1]
2020-02-18 10:07:06: /usr/share/passwall/subscribe.lua:304: node result is empty
2020-02-18 10:07:06: stack traceback:
	/usr/share/passwall/subscribe.lua:456: in function </usr/share/passwall/subscribe.lua:454>
	[C]: in function 'assert'
	/usr/share/passwall/subscribe.lua:304: in function 'update_node'
	/usr/share/passwall/subscribe.lua:445: in function </usr/share/passwall/subscribe.lua:429>
	[C]: in function 'xpcall'
	/usr/share/passwall/subscribe.lua:454: in main chunk
	[C]: ?
2020-02-18 10:07:06: 发生错误, 正在恢复服务

**Comment by fgprodigal** [comment]
这个你发给我做什么？
